name: test-action-CI

on: 
  push:
    branches: [ main ]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Copy file from GIT HUB
        uses: actions/checkout@v3
      - name: End
        run: echo "CI was END!"
