name: test-action-CI

on: 
  branches: main
    - [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Copy file from GIT HUB
        uses: action/checkout@v3
      - name: End
        run: echo "CI was END!"
