name: test-action-CI

on: 
  push:
    branches: [ main ]


jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Copy file from GIT HUB
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox py39
      - name: End
        run: echo "CI was END!" 